### ISSUE TITLE
Jinja templating exception when attempting the basic usage example

### ISSUE THREAD

**Issue by spacez320** [waynr/pyresume#99]
* PyResume Builder version: 0.1.2
* Python version: 2.7.14
* Operating System: Fedora 27 4.16.6-302.fc28.x86_64 x86_64 GNU/Linux

### Description

*Describe what you were trying to get done.*

Go through the basic usage example of PyResume as a beginning intro to using it.

*Tell us what happened, what went wrong, and what you expected to happen.*

Following the instructions here, https://pyresume.readthedocs.io/en/master/usage.html#basic, I copied the sample attributes file and tried to produce a .lex file from it. What I got was a Jinja templating exception.

### What I Did

```
matthew@helios resume $ pyresume create tex ./attributes.yaml > attributes.tex
Traceback (most recent call last):
  File "/home/matthew/.local/bin/pyresume", line 11, in <module>
    sys.exit(main())
  File "/home/matthew/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/matthew/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/matthew/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/matthew/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/matthew/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/matthew/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/matthew/.local/lib/python2.7/site-packages/pyresume/cli/__init__.py", line 48, in tex
    template = env.get_template('standard.tex')
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: standard.tex
```

**Comment by waynr** [comment]
hmm...I think this points to the need to improve testing by running tests from package rather than from source. I'll see what I can do to improve that and fix this bug tonight or tomorrow night.

**Comment by spacez320** [comment]
Thanks Wayne. Sorry to just heap on issues.

**Comment by waynr** [comment]
There's nothing for you to be sorry about. I'm grateful that you're discovering them since I obviously haven't done my due diligence as the maintainer of this software ;).

**Comment by spacez320** [comment]
Looks like the basic example is working from 0.1.3. Off to the races, thanks!
